export const scene = {
  title: 'ALIVE V4',
  room: 'ROOM ZERO',
  tagline: '先住下吧。',
  focus: '今天，先养这一件。',
  assets: {
    bed: './bed.png',
    table: './table.png',
    stool: './stool.png',
    window: './window.png',
    lamp: './lamp.png',
    rug: './rug.png',
    cup: './cup.png',
    resident: './zhanzhan-morning.png',
    smoke: './smoke-beast-encounter.png',
    liver: './liver-normal.png',
    muscle: './muscle-normal.png',
    water: './water-normal.png',
    egg: './egg-still.png',
    plant: './plant-stage-b.png',
    heart: './heart.png',
    note: './note-paper.png',
    tapeYellow: './tape-yellow.png',
    tapeRed: './tape-red.png',
    smokeIcon: './smoke-icon.png',
    speech: './speech-bubble.png',
    moodGood: './mood-good.svg',
    moodOkay: './mood-okay.svg',
    moodBad: './mood-bad.svg',
    navHouse: './nav-house.svg',
    navSearch: './nav-search.svg',
    navBook: './nav-book.svg',
    navPerson: './nav-person.svg',
  },
  actions: [
    { id: 'smoke', label: '抽烟', detail: '记录一支', accent: 'red', icon: './smoke-icon.png', character: './smoke-beast-encounter.png' },
    { id: 'drink', label: '喝酒', detail: '今天 Dry', accent: 'orange', character: './liver-normal.png' },
    { id: 'move', label: '运动', detail: '记录分钟', accent: 'yellow', character: './muscle-normal.png' },
    { id: 'water', label: '喝水', detail: '补一杯', accent: 'blue', character: './water-normal.png' },
    { id: 'food', label: '吃饭', detail: '记一餐', accent: 'green', character: './plant-stage-b.png' },
  ],
};
